#!/bin/bash
#-------------------------------------------------------------------------------
# Nek5000 configuration
#-------------------------------------------------------------------------------
# Nek version 
mver=17.0.4    #17.0.4 or 19.0.1

# source path 
SOURCE_ROOT="/home/saleh/Documents/installedPKG/portable/nek5000/Nek5000_v17"

# compilers
FC="mpif77"
CC="mpicc"

# pre-processor list (set to "?" to get a list of available symbols)
PPLIST="MPIIO"

#-------------------------------------------------------------------------------
# WHAT FOLLOWS ARE OPTIONAL SETTINGS
#-------------------------------------------------------------------------------

# optional compiler flags
FFLAGS="-I./inc_src -g" 
CFLAGS="-I./inc_src"

# optional linking flags
#USR_LFLAGS+=" -L/usr/lib -lfoo"

# auxilliary files to compile
USR="IO_tools.o chkpoint.o"

# MPI (default 1) 
#MPI=0

# profiling (default 1)
#PROFILING=0

# VisIt in situ (default 0)
#VISIT=1
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
if [ $mver == 17.0.4 ]
then	
   set -e
   # set defaults
   : ${SOURCE_ROOT:="$HOME/Nek5000"}
   : ${FC:="mpif77"}
   : ${CC:="mpicc"}
   : ${MPI:=1}
   : ${PROFILING:=1}
   : ${VISIT:=0}
   : ${PPLIST:=""}

   # overwrite source path with optional 2nd argument
   if [ -d $2 ] && [ $# -eq 2 ]; then
      SOURCE_ROOT="$2"
      echo "change source code directory to: ", $SOURCE_ROOT
   fi
   # create makefile
   source $SOURCE_ROOT/core/makenek.inc

   # compile 3rd_party code
   make_3rd_party 2>&1 | tee -a build.log

   # compile nek
   make -j4 -f makefile 2>&1 | tee -a build.log

elif [ $mver == 19.0.1 ]
then	
   set -a	
   echo "using source path: $SOURCE_ROOT"
   VERMAKENEK="19.0.1"
   set +a -e
   $SOURCE_ROOT/bin/nekconfig $@
   if [[ $1 != "clean" ]]; then
      $SOURCE_ROOT/bin/nekconfig -build-dep
      set -o pipefail
      make -j4 2>&1 | tee -a build.log
      set +o pipefail
   fi

fi	

exit 0
