#!/bin/bash

function error_quit {
    echo -e "$@"
    echo
    echo -e 'Usage:'
    echo -e './compile_script --clean'
    echo -e '   To clean build direcrtory. Makenek will ask for cleaning 3rd-party libraries.'
    echo
    echo -e './compile_script --all'
    echo -e '   To compile the code.'
    exit 1
}

# Add paths to the compression tool
export STREAM_SRC="/home/adalberto/TOOLS_iostream/streaming_adios2"
export STREAM_INC=" -I"${STREAM_SRC}

# Add path to ADIOS2 installation.
export ADIOS2_DIR=/home/adalberto/3rd_party_libs_tar/adios2-installation
export PATH=$ADIOS2_DIR/bin:$PATH
export ADIOS2=1
export ADIOS2_INCS=`adios2-config --cxx-flags`
export ADIOS2_LIBS=`adios2-config --cxx-libs`
export ADIOS2_FLAG=`adios2-config --cxx`

# Nek5000 parameters at the end of Ftn compiler, add where to find the tools
export CASE="turbPipe"
export NEK_SOURCE_ROOT="/home/adalberto/KTH_Framework_adios2/Nek5000"
export FC="/home/adalberto/3rd_party_libs/openmpi-4.1.1-installation/bin/mpifort"${STREAM_INC}
export CC="/home/adalberto/3rd_party_libs/openmpi-4.1.1-installation/bin/mpicc"
export CXX="/home/adalberto/3rd_party_libs/openmpi-4.1.1-installation/bin/mpicxx"
export FFLAGS="-mcmodel=medium"
export CFLAGS=""
export PPLIST=""
export USR="frame.o mntrlog_block.o mntrlog.o mntrtmr_block.o mntrtmr.o rprm_block.o rprm.o io_tools_block.o io_tools.o"
USR+=" chkpoint.o chkpt_mstp.o map2D.o stat.o stat_IO.o math_tools.o io_stream.o"
export USR_LFLAGS=""

# Compile the in-situ writer
#$CXX -o compressor ${COMPRESS_SRC}/ADIOS_compress.cpp $ADIOS2_FLAG

# Copy the config folder for the in-situ writer
cp -r ${STREAM_SRC}/config .


# arguments
args=("$@")
argsnr=$#

# check arguments
# parameters number check
if [ $[argsnr] -ne 1 ]; then
    error_quit 'Wrong arguments number!'
fi

for il in "$@"
do
case $il in
        --clean)
		rm compressor
		rm -r config
		${NEK_SOURCE_ROOT}/bin/makenek clean
                shift
                ;;
        --all)
                ${NEK_SOURCE_ROOT}/bin/makenek ${CASE}
                shift
                ;;
        *) 
                error_quit 'Wrong argument.'
                ;;
esac
done
