#!/bin/bash

# maximum number of elements
#MAXNEL=150000

# binary path
#bin_nek_tools=`cd ../bin && pwd`

# Fortran compiler
#FC="gfortran"
#FFLAGS=""

# C compiler
#CC="gcc"
#CFLAGS=""

# required by p4est
# C++ compiler
#CXX="mpicxx"

# linking flags
#LDFLAGS="-L$HOME/lib -lm"

source ./maketools.inc
